# Generated by Django 4.1.7 on 2024-04-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='Key',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
