# Generated by Django 4.1.7 on 2024-05-03 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geekom.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geekom', '0002_conversation_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(choices=[('BL', 'Blocked'), ('FR', 'Friend'), ('NR', 'No relation')], default='NR', max_length=2)),
                ('User_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first', to=settings.AUTH_USER_MODEL)),
                ('User_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='conversation',
            old_name='Owner',
            new_name='Creator',
        ),
        migrations.RemoveField(
            model_name='message',
            name='Image_id',
        ),
        migrations.AddField(
            model_name='conversation',
            name='Name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(default=None, upload_to=geekom.models.folder_path),
        ),
        migrations.AddField(
            model_name='users_conversation',
            name='Administrator',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
