# Generated by Django 4.1.7 on 2024-05-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geekom', '0003_status_list_rename_owner_conversation_creator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
    ]
