# Generated by Django 4.1.7 on 2024-05-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekom', '0004_remove_message_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_conversation',
            name='Administrator',
            field=models.BooleanField(default=False),
        ),
    ]
