# Generated by Django 4.1.7 on 2024-05-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekom', '0005_alter_users_conversation_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
